// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyZ0WqU6tR8GUIZDs4NQaf975Bk8zC13A',
    appId: '1:618219276946:web:5c9c5191a4fd1329fe344b',
    messagingSenderId: '618219276946',
    projectId: 'tour-7ff6e',
    authDomain: 'tour-7ff6e.firebaseapp.com',
    storageBucket: 'tour-7ff6e.firebasestorage.app',
    measurementId: 'G-V45FS17SG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKd9nuhoQvVCkGFR9R6CgrDiltHXxY8HM',
    appId: '1:618219276946:android:01b6775ada55e164fe344b',
    messagingSenderId: '618219276946',
    projectId: 'tour-7ff6e',
    storageBucket: 'tour-7ff6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPpCM1kROQWChEaWMtt4hoi-M6vEcQpNo',
    appId: '1:618219276946:ios:76c130d3da5d0bcbfe344b',
    messagingSenderId: '618219276946',
    projectId: 'tour-7ff6e',
    storageBucket: 'tour-7ff6e.firebasestorage.app',
    iosBundleId: 'com.example.tour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPpCM1kROQWChEaWMtt4hoi-M6vEcQpNo',
    appId: '1:618219276946:ios:76c130d3da5d0bcbfe344b',
    messagingSenderId: '618219276946',
    projectId: 'tour-7ff6e',
    storageBucket: 'tour-7ff6e.firebasestorage.app',
    iosBundleId: 'com.example.tour',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyZ0WqU6tR8GUIZDs4NQaf975Bk8zC13A',
    appId: '1:618219276946:web:03f171a702145673fe344b',
    messagingSenderId: '618219276946',
    projectId: 'tour-7ff6e',
    authDomain: 'tour-7ff6e.firebaseapp.com',
    storageBucket: 'tour-7ff6e.firebasestorage.app',
    measurementId: 'G-WDHH59D90X',
  );
}
